DROP TRIGGER IF EXISTS sync_on_upd;
CREATE TRIGGER sync_on_upd AFTER UPDATE ON ta
    FOR EACH ROW
    BEGIN
    UPDATE tb t SET t.`CREATE AT` = NEW.`CREATE AT`
    WHERE t.POINTER = NEW.POINTER;
    UPDATE tb t SET t.`LAST CHANGE AT` = NEW.`LAST CHANGE AT`
    WHERE t.POINTER = NEW.POINTER;
    UPDATE tb t SET t.TEAM = NEW.TEAM
    WHERE t.POINTER = NEW.POINTER;
    UPDATE tb t SET t.PROECESSOR = NEW.PROECESSOR
    WHERE t.POINTER = NEW.POINTER;
    UPDATE tb t SET t.`IS BUG` = NEW.`IS BUG`
    WHERE t.POINTER = NEW.POINTER;
    UPDATE tb t SET t.`IS FRONTEND BUG` = NEW.`IS FRONTEND BUG`
    WHERE t.POINTER = NEW.POINTER;
    UPDATE tb t SET t.`INTERNAL INCIDEN` = NEW.`INTERNAL INCIDEN`
    WHERE t.POINTER = NEW.POINTER;
    UPDATE tb t SET t.`IS IT TICKET` = NEW.`IS IT TICKET`
    WHERE t.POINTER = NEW.POINTER;
    UPDATE tb t SET t.`IS OUTBOUND` = NEW.`IS OUTBOUND`
    WHERE t.POINTER = NEW.POINTER;
    UPDATE tb t SET t.`IS MARKED` = NEW.`IS MARKED`
    WHERE t.POINTER = NEW.POINTER;
    UPDATE tb t SET t.WAVE = NEW.WAVE
    WHERE t.POINTER = NEW.POINTER;
    UPDATE tb t SET t.TIMEYEAR = NEW.TIMEYEAR
    WHERE t.POINTER = NEW.POINTER;
    UPDATE tb t SET t.SUBJECT = NEW.SUBJECT
    WHERE t.POINTER = NEW.POINTER;
    UPDATE tb t SET t.DESCRIPTION = NEW.DESCRIPTION
    WHERE t.POINTER = NEW.POINTER;
    UPDATE tb t SET t.OBJECTID = NEW.OBJECTID
    WHERE t.POINTER = NEW.POINTER;
    UPDATE tb t SET t.GUID = NEW.GUID
    WHERE t.POINTER = NEW.POINTER;
    UPDATE tb t SET t.UPDATED = NEW.UPDATED
    WHERE t.POINTER = NEW.POINTER;
    END


